Repository hoppscotch/hoppscotch, pull requests merged in 2019-12, with the labels that each got.

#391 App UI
  assets/css/styles.scss
  components/history.vue
  components/section.vue
  layouts/default.vue
  pages/graphql.vue
  pages/index.vue
  pages/realtime.vue
Labels: need testing

#400 Custom methods support
  assets/css/styles.scss
  pages/index.vue
  tests/e2e/integration/app.starter.spec.js
  tests/e2e/integration/feature.url-queries.spec.js
Labels: enhancement, need testing

#421 Header key autocompletion
  components/autocomplete.vue
  pages/graphql.vue
  pages/index.vue
Labels: enhancement

#432 chore: stick to Vue.js best practices
  components/collections/collection.vue
  components/collections/editCollection.vue
  components/collections/editFolder.vue
  components/collections/folder.vue
  components/collections/index.vue
  components/collections/saveRequestAs.vue
  layouts/default.vue
  pages/index.vue
Labels: enhancement, refactor
