Repository hoppscotch/hoppscotch, pull requests merged in 2019-11, with the labels that each got.

#244 Add brand new logo to the project
  README.md
  static/favicon.ico
  static/icon.png
  static/icons/icon-144x144.png
  static/icons/icon-192x192.png
  static/icons/icon-48x48.png
  static/icons/icon-512x512.png
  static/icons/icon-72x72.png
  static/icons/icon-96x96.png
  static/icons/logo.svg
  static/icons/postwoman.svg
  static/logo-onblack.svg
  static/logo-onwhite.svg
  static/logo.png
  static/screenshot.gif
  static/screenshot1.png
  static/screenshot2.png
Labels: discussion, enhancement

#246 Make page changes more fluid
  assets/css/styles.scss
Labels: bug fix

#282 Enhancement: make saving of collections, requests, folder more convenient
  components/collections/editCollection.vue
  components/collections/editFolder.vue
  components/collections/editRequest.vue
  components/collections/saveRequestAs.vue
Labels: enhancement

#288 Checking if seciton exist before accessing its properties
  layouts/default.vue
Labels: enhancement

#292 Replace highlight.js with ace editor.
  assets/css/styles.scss
  components/ace-editor.vue
  package-lock.json
  package.json
  pages/index.vue
  pages/settings.vue
  store/postwoman.js
Labels: WIP, enhancement

#303 Keyboard shortcuts
  assets/css/styles.scss
  components/collections/folder.vue
  components/collections/request.vue
  components/modal.vue
  layouts/default.vue
  pages/index.vue
Labels: enhancement

#316 feat: use alpine for Dockerfile
  Dockerfile
Labels: enhancement

#311 GraphQL Support
  assets/css/styles.scss
  components/graphql/field.vue
  components/graphql/type.vue
  layouts/default.vue
  package-lock.json
  package.json
  pages/graphql.vue
  pages/index.vue
  pages/settings.vue
  pages/websocket.vue
Labels: WIP, discussion, enhancement, help wanted

#319 GraphQL endpoint field is now persisted
  pages/graphql.vue
  store/mutations.js
  store/state.js
Labels: enhancement

#340 Separate dockerfile layers and add volume
  Dockerfile
  docker-compose.yml
Labels: bug fix, enhancement

#341 GraphQL Request Headers
  pages/graphql.vue
  store/mutations.js
  store/state.js
Labels: enhancement

#343 refactor: minor improvements
  components/collections/folder.vue
  components/collections/index.vue
  pages/graphql.vue
  pages/index.vue
  pages/realtime.vue
Labels: enhancement, refactor

#346 Added ability to run GraphQL queries
  pages/graphql.vue
  store/state.js
Labels: enhancement

#350 Undo header/param/body param deletion
  pages/graphql.vue
  pages/index.vue
Labels: enhancement

#344 ♻️ Refactor Functions
  assets/js/curlparser.js
  directives/textareaAutoHeight.js
  store/mutations.js
  store/postwoman.js
Labels: need testing, refactor

#351 Basic i18n support
  components/collections/index.vue
  components/history.vue
  lang/en-US.js
  lang/es-ES.js
  layouts/default.vue
  nuxt.config.js
  package-lock.json
  package.json
  pages/graphql.vue
  pages/index.vue
  pages/realtime.vue
  pages/settings.vue
Labels: core, enhancement

#379 Two Way Data Binding (v-model) to Ace Editor component
  components/ace-editor.vue
  pages/graphql.vue
  pages/index.vue
Labels: core, enhancement
