Repository hoppscotch/hoppscotch, pull requests merged in 2019-08, with the labels that each got.

#28 Added token based authentication type
  index.html
  script.js
Labels: enhancement, need testing

#44 Migrate Postwoman to Nuxt.js (full Vue and SCSS support)
  .gitignore
  404.html
  README.md
  assets/README.md
  assets/css/fonts.scss
  assets/css/styles.scss
  assets/js/pwa.js
  components/README.md
  index.html
  jsconfig.json
  layouts/README.md
  layouts/default.vue
  layouts/error.vue
  manifest.json
  middleware/README.md
  nuxt.config.js
  package-lock.json
  package.json
  pages/README.md
  pages/index.vue
  plugins/README.md
  script.js
  static/README.md
  static/favicon.ico
  static/icon.png
  static/icons/github.svg
  static/icons/icon-144x144.png
  static/icons/icon-192x192.png
  static/icons/icon-48x48.png
  static/icons/icon-512x512.png
  static/icons/icon-72x72.png
  static/icons/icon-96x96.png
  static/icons/logo.svg
  static/icons/pwalogo.svg
  static/screely.png
  static/screely2.png
  store/README.md
  sw.js
Labels: enhancement, future, need testing

#48 🔌 Add websocket support
  assets/css/styles.scss
  layouts/default.vue
  pages/index.vue
  pages/websocket.vue
Labels: enhancement, need testing

#55 🎨 Add theme support (and settings storage)
  assets/css/styles.scss
  assets/css/themes.scss
  components/logo.vue
  components/section.vue
  components/settings/swatch.vue
  layouts/default.vue
  nuxt.config.js
  package-lock.json
  package.json
  pages/index.vue
  pages/settings.vue
  pages/websocket.vue
  plugins/vuex-persist.js
  store/index.js
  store/postwoman.js
Labels: enhancement

#63 Feature/raw input
  pages/index.vue
Labels: enhancement, need testing

#68 Request headers
  assets/css/styles.scss
  pages/index.vue
Labels: enhancement, need testing

#73 Adds HTML preview.
  assets/css/styles.scss
  pages/index.vue
Labels: enhancement, need testing

#75 fixes #74 fallback for findEntryStatus when match is missing or other…
  assets/css/styles.scss
  pages/index.vue
Labels: enhancement, need testing

#79 Virtual scroll addition for history section.
  package.json
  pages/index.vue
Labels: enhancement, need testing

#80 Readable GitHub logo
  .gitignore
  layouts/default.vue
Labels: enhancement, need testing

#89 Websocket log auto scroll to bottom
  layouts/default.vue
  pages/settings.vue
  pages/websocket.vue
Labels: enhancement, need testing

#72 Enable shareable requests with parameters in url queries
  pages/index.vue
Labels: enhancement

#107 Sticky send button
  .editorconfig
  assets/css/styles.scss
  pages/index.vue
Labels: enhancement, need testing

#108 History fieldset height problem on mobile.
  components/history.vue
Labels: enhancement

#117 Add version number to footer and improves .editorconfig
  .editorconfig
  .gitignore
  assets/css/styles.scss
  build.js
  layouts/default.vue
  package.json
  pages/settings.vue
Labels: enhancement, need testing

#118 Bind history state and query params of requests
  pages/index.vue
Labels: enhancement, need testing

#123 ⌨️Add autocomplete widget with command line completion
  assets/css/themes.scss
  components/autocomplete.vue
  package-lock.json
  package.json
  pages/index.vue
Labels: enhancement
