Repository hoppscotch/hoppscotch, pull requests merged in 2019-10, with the labels that each got.

#182 updated threshold and rootMargin for IntersectionObserver
  pages/index.vue
Labels: bug fix

#185 Added auto theme
  assets/css/themes.scss
  pages/settings.vue
Labels: enhancement

#187 Add quotation marks for generated code
  pages/index.vue
Labels: bug fix, need testing

#181 Add basic e2e tests
  .travis.yml
  cypress.json
  package-lock.json
  package.json
  tests/e2e/fixtures/catapi.json
  tests/e2e/integration/app.starter.spec.js
  tests/e2e/integration/feature.url-queries.spec.js
  tests/e2e/support/commands.js
  tests/e2e/support/index.js
Labels: documentation, need testing

#184 Add Request name label for every requests
  components/history.vue
  pages/index.vue
Labels: enhancement, need testing

#197 Added Tooltips
  assets/css/styles.scss
  components/history.vue
  layouts/default.vue
  nuxt.config.js
  package-lock.json
  package.json
  plugins/v-tooltip.js
Labels: enhancement

#199 Fix CORS and mixed content issue
  nuxt.config.js
  pages/index.vue
  pages/settings.vue
  proxy/index.js
Labels: core, enhancement, need testing

#176 Collections
  components/collections/addCollection.vue
  components/collections/addFolder.vue
  components/collections/collection.vue
  components/collections/exportCollection.vue
  components/collections/folder.vue
  components/collections/index.vue
  components/collections/request.vue
  components/collections/saveRequest.vue
  pages/index.vue
  store/postwoman.js
Labels: WIP, enhancement, need testing

#205 Use returned value from toggle component on change event
  components/toggle.vue
  pages/index.vue
  pages/settings.vue
Labels: enhancement

#207 Feature/log errors
  pages/index.vue
Labels: enhancement

#213 Fix #212 Clear bearer token value
  pages/index.vue
Labels: bug fix

#215 Re-order sections and add toggle for including authentication in URL
  layouts/default.vue
  pages/index.vue
  store/postwoman.js
Labels: hacktoberfest

#217 Add the ApolloTV proxy server
  nuxt.config.js
  pages/index.vue
  pages/settings.vue
  proxy/index.js
Labels: enhancement

#211 bug: keeping information on page change
  pages/index.vue
  store/index.js
  store/mutations.js
  store/state.js
Labels: enhancement, need testing

#231 Feature/pre request script
  components/history.vue
  functions/preRequest.js
  functions/templating.js
  pages/index.vue
Labels: core, enhancement, need testing
