Repository hoppscotch/hoppscotch, pull requests merged in 2019-09, with the labels that each got.

#131 Bind raw body input to url of requests
  pages/index.vue
Labels: bug fix

#132 Copy requests
  pages/index.vue
Labels: core, enhancement, need testing

#136 Update url at keyup and at bodyParam/rawParam toggle state changes
  pages/index.vue
Labels: bug fix

#138 curl import added
  assets/js/curlparser.js
  components/modal.vue
  package.json
  pages/index.vue
Labels: core, enhancement

#142 Code highlighting
  assets/css/styles.scss
  package-lock.json
  package.json
  pages/index.vue
Labels: core, enhancement, need testing

#150 sort functionality added in history
  components/history.vue
Labels: enhancement, need testing

#146 .htaccess file added
  .htaccess
Labels: enhancement

#152 Sync path and parameters
  pages/index.vue
Labels: enhancement, need testing

#154 Post request headers issue resolved
  pages/index.vue
Labels: bug fix

#160 Fixed bug where hal+json responses are not rendered properly
  pages/index.vue
Labels: bug fix

#156 Sync path and parameters
  pages/index.vue
Labels: enhancement, need testing

#161 clear buttons added
  pages/index.vue
Labels: enhancement, need testing

#170 Activating Open Collective
  README.md
Labels: documentation
