Repository hoppscotch/hoppscotch, pull requests merged in 2020-01, with the labels that each got.

#479 GraphQL Type Highlight and Links
  components/graphql/argument.vue
  components/graphql/field.vue
  components/graphql/type.vue
  components/graphql/typelink.vue
  pages/graphql.vue
Labels: enhancement

#485 chore: Minor tweaks
  assets/js/oauth.js
Labels: refactor

#486 chore(oauth): Added method signatures as per JSDoc conventions
  assets/js/oauth.js
Labels: core, documentation, enhancement

#484 Porting (most of) code to typescript
  README.md
  assets/js/curlparser.js
  assets/js/oauth.js
  components/ace-editor.vue
  components/autocomplete.vue
  components/collections/addCollection.vue
  components/collections/addFolder.vue
  components/collections/collection.vue
  components/collections/editCollection.vue
  components/collections/editFolder.vue
  components/collections/editRequest.vue
  components/collections/folder.vue
  components/collections/importExportCollections.vue
  components/collections/index.vue
  components/collections/request.vue
  components/collections/saveRequestAs.vue
  components/graphql/field.vue
  components/graphql/type.vue
  components/graphql/typelink.vue
  components/history.vue
  components/logo.vue
  components/modal.vue
  components/section.vue
  components/settings/swatch.vue
  components/toggle.vue
  directives/textareaAutoHeight.ts
  functions/preRequest.ts
  functions/templating.js
  functions/templating.ts
  lang/en-US.js
  layouts/default.vue
  layouts/error.vue
  middleware/parsedefaulturl.js
  middleware/parsedefaulturl.ts
  package-lock.json
  package.json
  pages/doc.vue
  pages/graphql.vue
  pages/index.vue
  pages/realtime.vue
  pages/settings.vue
  plugins/v-tooltip.ts
  plugins/vuex-persist.js
  plugins/vuex-persist.ts
  store/index.ts
  store/mutations.js
  store/mutations.ts
  store/postwoman.ts
  store/state.js
  store/state.ts
  tsconfig.json
  vue-plugins.d.ts
  vue-virtual-scroll-list.d.ts
Labels: core, refactor

#487 Network Strategies
  functions/network.js
  functions/strategies/AxiosStrategy.js
  functions/strategies/ProxyStrategy.js
  pages/graphql.vue
  pages/index.vue
Labels: core, enhancement, refactor

#494 Firefox Extension compatibility
  functions/network.js
  functions/strategies/AxiosStrategy.js
  functions/strategies/FirefoxStrategy.js
  functions/strategies/ProxyStrategy.js
Labels: core, enhancement

#500 Refactoring proxy handling to be done in strategies
  functions/network.js
  functions/strategies/AxiosStrategy.js
  functions/strategies/FirefoxStrategy.js
  functions/strategies/ProxyStrategy.js
Labels: core, enhancement, refactor

#505 Syntax Error marking in GraphQL query editor
  components/graphql/queryeditor.vue
  functions/utils/debounce.js
  pages/graphql.vue
Labels: enhancement

#508 GraphQL query validation based on schema
  components/graphql/queryeditor.vue
  pages/graphql.vue
Labels: enhancement

#510 Validate duplicate collections
  store/postwoman.js
Labels: bug fix

#512 Support for Google Chrome Extension
  README.md
  functions/network.js
  functions/strategies/ChromeStrategy.js
  functions/strategies/FirefoxStrategy.js
  layouts/default.vue
Labels: core, enhancement

#516 Validations for edit and create collections activity
  components/collections/addCollection.vue
  components/collections/editCollection.vue
  store/postwoman.js
Labels: bug fix

#518 Feature/post request tests
  functions/postwomanTesting.js
  pages/index.vue
Labels: WIP

#531 Enhancements
  assets/css/styles.scss
  functions/postwomanTesting.js
  pages/index.vue
Labels: core, refactor

#534 Updated GraphQL Query Variable Editor
  pages/graphql.vue
  store/mutations.js
  store/state.js
Labels: enhancement, refactor
