Repository hoppscotch/hoppscotch, pull requests merged in 2020-02, with the labels that each got.

#548 fix(chore): Take letter casing into account while checking for duplicate collection
  store/postwoman.js
Labels: bug fix

#549 Show Ctrl instead of Command for shortcuts non-Apple platforms
  layouts/default.vue
Labels: enhancement

#551 Added toggle to decide whether extensions should be used
  functions/network.js
  lang/en-US.js
  pages/settings.vue
  store/postwoman.js
Labels: enhancement

#556 Fixed typo in translation file for Auto theme
  lang/en-US.js
Labels: bug

#559 chore: use typeof as an operator and make use of localizable strings
  components/collections/addCollection.vue
  components/collections/editCollection.vue
  functions/network.js
  lang/en-US.js
  pages/settings.vue
Labels: core, refactor

#566 Moved common headers to a separate file
  functions/headers.js
  pages/graphql.vue
  pages/index.vue
Labels: refactor

#572 fix: drop the toast which doesn't show up
  layouts/default.vue
Labels: core

#574 Postman collection parsing
  components/collections/importExportCollections.vue
  lang/en-US.js
Labels: core, enhancement

#590 GraphQL Query Autocompletion
  components/graphql/queryeditor.vue
  package-lock.json
  package.json
Labels: enhancement

#594 POST request body editor reacts to the content type
  functions/editorutils.js
  pages/index.vue
Labels: enhancement

#591 Environment Mangement
  components/collections/importExportCollections.vue
  components/environments/addEnvironment.vue
  components/environments/editEnvironment.vue
  components/environments/environment.vue
  components/environments/importExportEnvironment.vue
  components/environments/index.vue
  functions/fb.js
  lang/en-US.js
  pages/index.vue
  pages/settings.vue
  store/postwoman.js
Labels: core, enhancement

#595 Added settings toggle for enabling/disabling auto scrolling (scrollInto functionality)
  lang/en-US.js
  pages/graphql.vue
  pages/index.vue
  pages/settings.vue
  store/postwoman.js
Labels: core

#605 JSON linting in the code editor
  components/ace-editor.vue
  functions/jsonParse.js
Labels: enhancement

#602 GraphQL page improvements, and more
  .huskyrc
  .prettierrc
  components/ace-editor.vue
  components/section.vue
  functions/jsonParse.js
  layouts/default.vue
  package.json
  pages/graphql.vue
  pages/index.vue
  pages/realtime.vue
  store/mutations.js
  store/state.js
Labels: enhancement

#609 Fixed install extension toast appearing even when extension is installed
  layouts/default.vue
Labels: bug fix

#612 :bug: FIxed URI not updating on Clear content, minor formData improve…
  pages/index.vue
Labels: bug fix

#618 Link multiple auth providers
  components/firebase/login.vue
  lang/en-US.js
  pages/settings.vue
Labels: bug fix, critical

#620 Added shortcut to quickly run the GraphQL query
  components/graphql/queryeditor.vue
  functions/platformutils.js
  layouts/default.vue
  pages/graphql.vue
Labels: enhancement

#629 Ignore empty GQL Variable Strings
  pages/graphql.vue
Labels: enhancement

#623 test: purge travis
  .travis.yml
  tests/e2e/integration/proxy.spec.js
Labels: enhancement, need information
