Repository hoppscotch/hoppscotch, pull requests merged in 2020-05, with the labels that each got.

#838 GraphQL Query Editor Syntax Highlighting
  components/graphql/queryeditor.vue
  functions/syntax/gqlQueryLangMode.js
Labels: enhancement

#840 URL Path Parameters #834
  functions/requestParams.js
  functions/templating.js
  pages/index.vue
  store/mutations.js
Labels: enhancement, need testing

#846 Save GraphQL Docs
  package-lock.json
  package.json
  pages/graphql.vue
  store/state.js
Labels: enhancement

#847 Add format body option
  lang/en-US.json
  pages/index.vue
Labels: enhancement

#862 Allow importing environment variables via Postman environment json files
  components/environments/importExportEnvironment.vue
Labels: enhancement

#876 Make Realtime page URL validations more lenient
  functions/utils/valid.js
Labels: bug fix

#878 Fix syncing environments
  components/environments/index.vue
Labels: bug fix

#881 Fixed Axios parsing JSON for non-JSON content-types
  functions/strategies/AxiosStrategy.js
  package-lock.json
Labels: bug fix

#890 Fixed regex not validating for Realtime page for localhost URLs
  functions/utils/valid.js
Labels: bug fix

#893 Some small refactoring
  components/realtime/sse.vue
  functions/utils/contenttypes.js
  functions/utils/valid.js
  pages/index.vue
Labels: refactor

#895 Added check if content-type header is present for transformResponse
  functions/strategies/AxiosStrategy.js
Labels: bug fix

#915 Cancellable Requests
  functions/network.js
  functions/strategies/AxiosStrategy.js
  functions/strategies/ExtensionStrategy.js
  lang/en-US.json
  pages/index.vue
Labels: feature
